### ISSUE TITLE
getUserPublicKey

### ISSUE THREAD

**Issue by amodi01** [decentraland-scenes/Awesome-Repository#3]
import { getUserPublicKey } from "@decentraland/Identity"

const publicKeyRequest = executeTask(async () => {
  const publicKey = await getUserPublicKey()
  log(publicKey)
  return publicKey
})

I am creating a POC. My we app is connected to Metmask. But the above code is giving null value for public key.

**Comment by kinsq** [comment]
do you have a contract live?
if so, post the contract address.
I'd be excited to beta test your app.

thx

**Comment by nearnshaw** [comment]
This issue seems outdated, I'm going to close this

The above method should work to fetch a player's eth address from Metamask, make sure you're running a preview that is connected via Metamask

There are now other ways to obtain that same data too, see:
https://docs.decentraland.org/development-guide/user-data/#get-player-data
