### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by grantwwoodford** [decentraland-scenes/Awesome-Repository#5]
I am running Ubuntu 18.04.5.
Node.js v8.10.0
npm: 6.14.10 

I have installed dependencies: `npm i -g decentraland`

For all the examples when I run `dcl start` I get the following error:

> /usr/local/lib/node_modules/decentraland/dist/cli.js:3
> !function(t){var r={};function n(i){if(r[i])return r[i].exports;var o=r[i]={i:i,l:!1,exports:{}};return t[i].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=t,n.c=r,n.d=function(t,r,i){n.o(t,r)||Object.defineProperty(t,r,{enumerable:!0,get:i})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,r){if(1&r&&(t=n(t)),8&r)return t;if(4&r&&"object"==typeof t&&t&&t.__esModule)return t;var i=Object.create(null);if(n.r(i),Object.defineProperty(i,"default",{enumerable:!0,value:t}),2&r&&"string"!=typeof t)for(var o in t)n.d(i,o,function(r){return t[r]}.bind(null,o));return i},n.n=function(t){var r=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(r,"a",r),r},n.o=function(t,r){return Object.prototype.hasOwnProperty.call(t,r)},n.p="",n(n.s=557)}([function(t,r,n){"use strict";n.r(r),n.d(r,"__extends"
> 
> SyntaxError: Unexpected reserved word
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:616:28)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:188:16)
>     at bootstrap_node.js:609:3

Any idea what is wrong?

**Comment by grantwwoodford** [comment]
Ok, I have figured this out. Seems like the default nodejs version in Ubuntu is out of date. 

After running:
 `curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -`
and then:
 `sudo apt-get install -y nodejs`
it is not working. 

It would be nice to point this out somewhere in the documentation though. I did not see a section to even check if you are running the correct version. Where would you add this?

**Comment by nearnshaw** [comment]
It sounds to me like this is an issue that is out of scope of the installation of the Decentraland CLI. 
We can't be documenting possible issues with the entire stack of technology for every possible operating system

This seems like the kind of thing that would be good to add as a note on Stack Overflow, so that someone with the same issue can google it, but it doesn't sound like it fits into the docs.

If you'd like to add a mention of this in Stack Overflow, that would be really aprreciated:
https://stackoverflow.com/questions/tagged/decentraland-ecs

(not a lot of people are using Stack Overflow for Decentraland, they tend to ask questions on Discord, but we should really push them to use this more)
